config/routes.rb
Rails.application.routes.draw do
  get '/' => 'home#index'
  resources :users do
    resources :photos
  end

  resources :tags, only: [:create, :destroy]
  get '/log-in' => "sessions#new"
  post '/log-in' => "sessions#create"
  get '/log-out' => "sessions#destroy", as: :log_out

end

app/models/photo.rb
class Photo<ActiveRecord::Base
  belongs_to :user
  has_many :tags

  has_attached_file :image, :styles => { :medium => "300x300>", :thumb => "100x100>" }, :default_url => "/images/:style/missing.png"
  validates_attachment_content_type :image, :content_type => /\Aimage\/.*\Z/
end

app/models/tag.rb
class Tag<ActiveRecord::Base
  belongs_to :user
  belongs_to :photo
end

app/models/user.rb
class User<ActiveRecord::Base
  has_many :photos
  has_many :tags
  attr_accessor :password
  has_attached_file :avatar, :styles => { :medium => "300x300>", :thumb => "100x100>" }
  validates_attachment_content_type :avatar, :content_type => /\Aimage\/.*\Z/
  validates_confirmation_of :password
  before_save :encrypt_password
  validates :email, uniqueness: true

  validates :email, :presence => true
  def encrypt_password
    self.password_salt = BCrypt::Engine.generate_salt
    self.password_hash = BCrypt::Engine.hash_secret(password, password_salt)
  end

  def is_email?
    self.email.include?('@') && self.email.include?('.')
  end

  def self.authenticate(email, password)
    user = User.where(email: email).first
    if user && user.password_hash == BCrypt::Engine.hash_secret(password, user.password_salt)
      user
    else
      nil
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end
  helper_method :current_user
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/photos_controller.rb
class PhotosController < ApplicationController
  def create
    @user = User.find(params[:user_id])
    if params[:photo] == nil

      flash[:alert] = "Please upload a photo"
      redirect_to :back
    else
    @photo = Photo.create(photo_params)
      @photo.user_id = @user.id
      @photo.save
      flash[:notice] = "Successfully uploaded a photo"
      redirect_to user_path(@user)
    end
  end

  def new
    @user = User.find(params[:user_id])
    @photo = Photo.create()
  end

  private
  def photo_params
    params.require(:photo).permit(:image)
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
    @user = User.authenticate(params[:email], params[:password])
    if @user
      flash[:notice] = "You've been logged in."
      session[:user_id] = @user.id
      redirect_to user_path(@user)
    else
      flash[:alert] = "There was a problem logging you in!"
      redirect_to log_in_path
    end
  end

  def destroy
    session[:user_id] = nil
    flash[:notice] = "You've been logged out successfully."
    redirect_to "/"
  end

end

app/controllers/tags_controller.rb
class TagsController<ActionController::Base
  def new
    redirect_to "/"
  end

  def create
    @user = User.find(params[:tag][:user_id])
    @tag = Tag.create({user_id: params[:tag][:user_id], photo_id: params[:tag][:photo_id]})
    redirect_to user_path(session[:user_id])
  end




end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def create
    @user = User.new(user_params)
    @user.valid?
    if !@user.is_email?
      flash[:alert] = "Input a properly formatted email."
      redirect_to :back
    elsif @user.errors.messages[:email] != nil
      flash[:notice]= "That email " + @user.errors.messages[:email].first
      redirect_to :back
    elsif @user.save
      flash[:notice]= "Welcome to the site!"
      redirect_to user_path(@user)
    else
      flash[:alert] = "There was a problem creating your account. Please try again."
      redirect_to :back
    end
  end

  def new
  end

  def show
    @users = User.all
    @user = User.find(params[:id])
    @tag = Tag.new
  end

  private

    def user_params
      params.require(:user).permit(:email, :password, :password_confirmation, :avatar)
  end


end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/home/index.html.erb
<h1>Treegram </h1>
<h2>Your Favorite Tree Photosharing Service</h2>
<div class="row">
  <div class="col-sm-4">
    <%= link_to 'Login', log_in_path, class: ["btn", "btn-success", 'btn-lg'] %>
    <%= link_to 'Sign Up', new_user_path, class: ['btn', 'btn-success', 'btn-lg'] %>
  </div>
  <div class="col-sm-7">
      <%= image_tag "background.jpg" %>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>PhotoShare</title>
  <link href='http://fonts.googleapis.com/css?family=Open+Sans+Condensed:300' rel='stylesheet' type='text/css'>
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.4/css/bootstrap.min.css">
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>

<body>
  <div class="container">
    <%= flash[:alert] %>
    <%= flash[:notice] %>
    <%= yield %>

  </div>
</body>
</html>

app/views/photos/new.html.erb
<h1>Add a Photo</h1>
<%= form_for Photo.new(), :url => user_photos_path, :html => {:multipart => true} do |form| %>
  <%= form.file_field :image %>
  <%= form.submit 'Upload'%>
<% end %>

app/views/photos/show.html.erb
<%= image_tag @photo.image.url %>
<%= image_tag @photo.image.url(:thumb) %>

app/views/users/new.html.erb
<h1>Sign Up</h1>
<%=form_for User.new, class: "form-inline" do |f| %>
<%=f.label :email %>
<%=f.text_field :email %>
<%=f.label :password %>
<%=f.password_field :password %>
<%=f.label :password_confirmation %>
<%=f.password_field :password_confirmation %>
<br>
<%=f.label :avatar, 'Upload Avatar' %>
<%= f.file_field :avatar %>
<br>
<%=f.submit "Sign Up" %>
<%end%>

app/views/users/show.html.erb
<div class = "row top_row">
  <div class="col-sm-6 user_att">
    <h2><%= @user.email%></h2>
    <% if @user.avatar_file_name %>
      <%= image_tag @user.avatar.url(:thumb) %>
    <% end %>
  </div>
  <div class="col-sm-6">
    <%= link_to 'Logout', log_out_path, class: ['btn', 'btn-danger', 'logout_btn'] %>
  </div>
  <div class="row">
    <%= link_to 'Add Photo', new_user_photo_path(@user), class: ['btn', 'btn-success', 'add_photo_btn'] %>
  </div>
</div>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<div class="row" >

<% @user.photos.each  do |photo|  %>

<div class="well col-sm-4">
  <%= image_tag photo.image.url(:medium) %>

  <%= form_for @tag do |f| %>
    <%= f.hidden_field :photo_id, value: photo.id %>
    <%= f.collection_select :user_id, @users, :id, :email %>
    <%= f.submit "Tag User" %>
  <% end %>

  <% photo.tags.each do |tag| %>
    <%= tag.user.email %>
  <% end %>

</div>
<% end %>

</div>